### ISSUE TITLE
convert/ mmCIF output is not valid according to the PDBx/mmCIF dictionary

### ISSUE THREAD

**Issue by bienchen** [project-gemmi/gemmi#178] opened 2022-01-19 15:10 UTC
When I run `gemmi convert <FILE>.pdb <FILE>.cif`, the produced mmCIF file is not valid according to the PDBx/mmCIF dictionary. Running `CifCheck` (https://github.com/rcsb/cpp-dict-pack) tells me that category `entity_poly` is missing. Category `entity_poly_seq` is also only produced when invoking `-s`. Would be nice to get a mmCIF file out of `convert` that passes checking with the PDBx/mmCIF dictionary.

**Comment by wojdyr** [comment] 2022-01-19 17:40
Having `entity_poly` caused a problem during deposition, so in 8692e4cb9f8a31abb789dda01b26542d164c7a19 writing it was disabled by default.
Is this validator always complaining about missing `entity_poly`, or only when `entity_poly_seq` is present?
This category is not mandatory in the dictionary (no category is mandatory):
```
    _category.id                  entity_poly
    _category.mandatory_code      no
```

**Comment by bienchen** [comment] 2022-01-20 08:39
Thanks for looking into this.

When I `convert` without `-s` I get
```
++ERROR - In block "test", parent category "entity_poly_seq", of category "atom_site", is missing.
++ERROR - In block "test", parent category "pdbx_poly_seq_scheme", of category "atom_site", is missing.
```

Running `convert` with `-s` gives me
```
++ERROR - In block "test", parent category "entity_poly", of category "entity_poly_seq", is missing.
++ERROR - In block "test", parent category "pdbx_poly_seq_scheme", of category "atom_site", is missing.
```

I'm using `CifCheck` from https://github.com/rcsb/cpp-dict-pack which is from RCSB. My guess is they are using it themselves to validate mmCIF files.

`entity_poly_seq` can't be mandatory since you can produce a mmCIF file without any polymeric molecular entity. You could write a mmCIF file with a single ion in it, no protein, no nucleic acid and it still would be a valid mmCif file while that file can't have `entity_poly_seq` because... no polymer ;) I guess once you have a linear polymer in a mmCIF file, `entity_poly_seq` should be in there, too. That can't be reflected by mmCIF dictionaries since they don't know conditionals.

**Comment by wojdyr** [comment] 2022-01-20 10:37
It's good to see more people exploring the mmCIF specification and tools.

> I'm using `CifCheck` from https://github.com/rcsb/cpp-dict-pack which is from RCSB. My guess is they are using it themselves to validate mmCIF files.

I'm sure they do, but not to validate the files uploaded during deposition. If you start a deposition or use the validation service at https://validate.wwpdb.org you won't get such errors.

> `entity_poly_seq` can't be mandatory since you can produce a mmCIF file without any polymeric molecular entity.

It's rather because the CCD and structure factor files wouldn't validate.

> You could write a mmCIF file with a single ion in it, no protein, no nucleic acid and it still would be a valid mmCif file while that file can't have `entity_poly_seq` because... no polymer ;)

Wouldn't CifCheck show the same errors about missing categories for a file with a single ion?

It would be trivial to add a minimal `entity_poly` category, older versions of gemmi did this and there is an option in the code to enable it. But there is no practical use of it, and there is a practical problem when people try to deposit such files and get errors.

**Comment by bienchen** [comment] 2022-01-20 12:27
OK, then I go back to RCSB to figure out some questions, next. Did you raise the deposition issue with `entity_poly` at the deposition site?

**Comment by wojdyr** [comment] 2022-01-20 13:24
I don't what to go into the details of the deposition here.

The mmCIF files from the PDB have a number of redundant tables. I'm not trying to reproduce them all. I think the ones that are useful are already generated. Another problem with adding more things to the generated mmCIF files is that there is no easy way to check if depositing such files to the PDB still works (the only way I know of is asking someone from the PDB to test it).
So currently I don't plan to work on entity_poly and pdbx_poly_seq_scheme, but of course this may change when we have new reasons to do this.

**Comment by CV-GPhL** [comment] 2022-02-17 14:13
Two additional two items that this checker shows:

- missing mandatory item [type_symbol](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_atom_site_anisotrop.type_symbol.html) in category [atom_site_anisotrop](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/atom_site_anisotrop.html)
- mandatory item [_struct_mon_prot_cis.label_seq_id](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_struct_mon_prot_cis.label_seq_id.html) has invalid value "?": the corresponding [_atom_site.label_seq_id](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_atom_site.label_seq_id.html) is given as ".". Both settings relate to the missing [entity_poly_seq](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/entity_poly_seq.html) category?

**Comment by wojdyr** [comment] 2022-02-17 15:35
IIUC the last message complains that the null value is `?` and not `.`. I applied a blind fix for this.
I will also add `_atom_site_anisotrop.type_symbol` – it's redundant, but shouldn't do any harm.

**Comment by CV-GPhL** [comment] 2022-02-17 15:49
@wojdyr Thanks a lot.

Agree,  that should be redundant (not sure why it is defined as mandatory). It might even be a case where a mmCIF file that is in principle invalid (according to the PDBx/mmCIF dictionary) is fine e.g. for deposition ... but we don't know what subset is used internally by OneDep.

**Comment by wojdyr** [comment] 2022-02-17 18:10
Yes, the opposite can also be true: making file more conforming to the dictionary can make it not acceptable for deposition.

**Closed** 2022-07-25 20:38 UTC
