### ISSUE TITLE
I still suggest  gemmi  can  generate crystal slab or surface. Thanks!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [project-gemmi/gemmi#334] opened 2024-09-13 09:51 UTC

**Comment by wojdyr** [comment] 2024-09-13 10:52
Duplicate of #107 and #189.
It'd be better to add comments to your previous requests rather than opening new ones.
Anyway, it's still not in the scope of this project.

**Closed** 2024-09-13 10:53 UTC
